export const users = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    age: 28,
    role: "admin",
    isActive: true,
    joinedAt: "2022-03-15",
    address: { city: "New York", country: "USA" },
    scores: [88, 92, 75, 96],
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    age: 34,
    role: "editor",
    isActive: false,
    joinedAt: "2021-07-22",
    address: { city: "London", country: "UK" },
    scores: [70, 65, 80, 74],
  },
  {
    id: 3,
    name: "Clara Lee",
    email: "clara@example.com",
    age: 22,
    role: "viewer",
    isActive: true,
    joinedAt: "2023-01-10",
    address: { city: "Seoul", country: "South Korea" },
    scores: [95, 98, 100, 91],
  },
  {
    id: 4,
    name: "David Kim",
    email: "david@example.com",
    age: 40,
    role: "editor",
    isActive: true,
    joinedAt: "2020-11-05",
    address: { city: "Toronto", country: "Canada" },
    scores: [60, 72, 68, 77],
  },
  {
    id: 5,
    name: "Eva Martinez",
    email: "eva@example.com",
    age: 26,
    role: "viewer",
    isActive: false,
    joinedAt: "2023-06-30",
    address: { city: "Madrid", country: "Spain" },
    scores: [85, 89, 90, 88],
  },
  {
    id: 6,
    name: "Frank Nguyen",
    email: "frank@example.com",
    age: 31,
    role: "admin",
    isActive: true,
    joinedAt: "2019-04-18",
    address: { city: "Sydney", country: "Australia" },
    scores: [55, 60, 58, 63],
  },
];

export const products = [
  {
    id: 101,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 89.99,
    stock: 23,
    rating: 4.5,
    discount: 0,
    tags: ["audio", "wireless", "portable"],
  },
  {
    id: 102,
    name: "Running Shoes",
    category: "Sports",
    price: 120.0,
    stock: 0,
    rating: 4.2,
    discount: 0,
    tags: ["running", "outdoor", "fitness"],
  },
  {
    id: 103,
    name: "Coffee Maker",
    category: "Kitchen",
    price: 55.5,
    stock: 8,
    rating: 3.9,
    discount: 5,
    tags: ["coffee", "appliance", "morning"],
  },
  {
    id: 104,
    name: "JavaScript: The Good Parts",
    category: "Books",
    price: 29.99,
    stock: 50,
    rating: 4.8,
    discount: 0,
    tags: ["programming", "javascript", "education"],
  },
  {
    id: 105,
    name: "Yoga Mat",
    category: "Sports",
    price: 35.0,
    stock: 15,
    rating: 4.6,
    discount: 15,
    tags: ["yoga", "fitness", "indoor"],
  },
  {
    id: 106,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 149.99,
    stock: 5,
    rating: 4.7,
    discount: 0,
    tags: ["keyboard", "gaming", "typing"],
  },
  {
    id: 107,
    name: "Blender",
    category: "Kitchen",
    price: 44.0,
    stock: 12,
    rating: 3.5,
    discount: 20,
    tags: ["blender", "smoothie", "appliance"],
  },
  {
    id: 108,
    name: "Notebook A5",
    category: "Stationery",
    price: 8.99,
    stock: 200,
    rating: 4.1,
    discount: 0,
    tags: ["writing", "notes", "paper"],
  },
];

export const orders = [
  {
    id: 1001,
    userId: 1,
    status: "delivered",
    createdAt: "2024-01-10",
    items: [
      { productId: 101, quantity: 1 },
      { productId: 104, quantity: 2 },
    ],
  },
  {
    id: 1002,
    userId: 3,
    status: "pending",
    createdAt: "2024-03-22",
    items: [{ productId: 106, quantity: 1 }],
  },
  {
    id: 1003,
    userId: 4,
    status: "cancelled",
    createdAt: "2024-02-14",
    items: [
      { productId: 103, quantity: 1 },
      { productId: 107, quantity: 1 },
    ],
  },
  {
    id: 1004,
    userId: 1,
    status: "shipped",
    createdAt: "2024-04-05",
    items: [{ productId: 105, quantity: 2 }],
  },
  {
    id: 1005,
    userId: 6,
    status: "delivered",
    createdAt: "2024-04-18",
    items: [
      { productId: 108, quantity: 5 },
      { productId: 104, quantity: 1 },
    ],
  },
];

export const tasks = [
  {
    id: 1,
    title: "Set up project structure",
    assignedTo: 1,
    priority: "high",
    completed: true,
    dueDate: "2024-01-15",
    tags: ["setup", "planning"],
  },
  {
    id: 2,
    title: "Write unit tests",
    assignedTo: 2,
    priority: "medium",
    completed: false,
    dueDate: "2024-02-20",
    tags: ["testing", "quality"],
  },
  {
    id: 3,
    title: "Design database schema",
    assignedTo: 4,
    priority: "high",
    completed: true,
    dueDate: "2024-01-20",
    tags: ["database", "planning"],
  },
  {
    id: 4,
    title: "Fix login bug",
    assignedTo: 1,
    priority: "high",
    completed: false,
    dueDate: "2024-03-01",
    tags: ["bug", "auth"],
  },
  {
    id: 5,
    title: "Update documentation",
    assignedTo: 3,
    priority: "low",
    completed: false,
    dueDate: "2024-04-10",
    tags: ["docs"],
  },
  {
    id: 6,
    title: "Deploy to staging",
    assignedTo: 6,
    priority: "medium",
    completed: true,
    dueDate: "2024-03-15",
    tags: ["devops", "deployment"],
  },
  {
    id: 7,
    title: "Code review PR #42",
    assignedTo: 2,
    priority: "medium",
    completed: false,
    dueDate: "2024-04-22",
    tags: ["review"],
  },
  {
    id: 8,
    title: "Optimize slow queries",
    assignedTo: 4,
    priority: "high",
    completed: false,
    dueDate: "2024-05-01",
    tags: ["performance", "database"],
  },
];
